spring:
  main:
    banner-mode: "OFF"

logging:
  level:
    root: "INFO"
    org.springframework.boot: "INFO"
  config: "classpath:log-config.xml"

# https://www.baeldung.com/spring-boot-context-path
server:
  port: "8000"