spring:
  main:
    banner-mode: "OFF"

logging:
  level:
    ROOT: INFO
    org.springframework.boot: INFO
    org.beyene.*: DEBUG
# config can be omitted due to autodiscover when named logback.xml
# logging/config: "classpath:log-config.xml"

# https://www.baeldung.com/spring-boot-context-path
server:
  port: "8000"

# https://www.baeldung.com/spring-boot-shutdown
# https://www.baeldung.com/java-restart-spring-boot-app
management:
  security.enabled: "false"
  endpoint:
    shutdown.enabled: "true"
    restart.enabled: "true"
  endpoints:
    web.exposure.include: "shutdown, restart"
    web.base-path: ""
