export const SET_REQUEST_ACTIVE = 'SET_REQUEST_ACTIVE';

export const SUBMIT_OFFER = 'SUBMIT_OFFER';
export const SUBMIT_OFFER_START = 'SUBMIT_OFFER_START';
export const SUBMIT_OFFER_ERROR = 'SUBMIT_OFFER_ERROR';

export const FETCH_REQUEST = 'FETCH_REQUEST';
export const FETCH_REQUEST_ERROR = 'FETCH_REQUEST_ERROR';

export const FETCH_OFFERS = 'FETCH_OFFERS';
export const FETCH_OFFERS_START = 'FETCH_OFFERS_START';
export const FETCH_OFFERS_ERROR = 'FETCH_OFFERS_ERROR';

export const FETCH_RESERVATIONS = 'FETCH_RESERVATIONS';
export const FETCH_RESERVATIONS_START = 'FETCH_RESERVATIONS_START';
export const FETCH_RESERVATIONS_ERROR = 'FETCH_RESERVATIONS_ERROR';

export const UPDATE_RESERVATION = 'UPDATE_RESERVATION';
export const UPDATE_RESERVATION_START = 'UPDATE_RESERVATION_START';
export const UPDATE_RESERVATION_ERROR = 'UPDATE_RESERVATION_ERROR';
export const UPDATE_RESERVATION_RESET = 'UPDATE_RESERVATION_RESET';
