export const FETCH_REQUEST = 'FETCH_REQUEST';
export const FETCH_REQUEST_ERROR = 'FETCH_REQUEST_ERROR';

export const SUBMIT_REQUEST = 'SUBMIT_REQUEST';
export const SUBMIT_REQUEST_START = 'SUBMIT_REQUEST_START';
export const SUBMIT_REQUEST_ERROR = 'SUBMIT_REQUEST_ERROR';

export const FETCH_OFFERS = 'FETCH_OFFERS';
export const FETCH_OFFERS_START = 'FETCH_OFFERS_START';
export const FETCH_OFFERS_ERROR = 'FETCH_OFFERS_ERROR';

export const FETCH_RESERVATION = 'FETCH_RESERVATION';
export const FETCH_RESERVATION_ERROR = 'FETCH_RESERVATION_ERROR';
export const FETCH_RESERVATION_RESET = 'FETCH_RESERVATION_RESET';

export const SUBMIT_RESERVATION = 'SUBMIT_RESERVATION';
export const SUBMIT_RESERVATION_START = 'SUBMIT_RESERVATION_START';
export const SUBMIT_RESERVATION_ERROR = 'SUBMIT_RESERVATION_ERROR';

export const UPDATE_RESERVATION = 'UPDATE_RESERVATION';
export const UPDATE_RESERVATION_START = 'UPDATE_RESERVATION_START';
export const UPDATE_RESERVATION_ERROR = 'UPDATE_RESERVATION_ERROR';
export const UPDATE_RESERVATION_RESET = 'UPDATE_RESERVATION_RESET';
