// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dtos.proto

package org.beyene.protocol.tcp.message;

public final class Dto {
  private Dto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Request_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Request_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Offer_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Offer_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ForwardOffer_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ForwardOffer_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Reservation_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Reservation_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ReservationAction_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ReservationAction_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ReservationPaymentOption_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ReservationPaymentOption_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Message_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Message_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\ndtos.proto\032\037google/protobuf/timestamp." +
      "proto\"o\n\007Request\022\016\n\006source\030\001 \001(\t\022\n\n\002id\030\002" +
      " \001(\t\022\016\n\006energy\030\003 \001(\001\022(\n\004date\030\004 \001(\0132\032.goo" +
      "gle.protobuf.Timestamp\022\016\n\006window\030\005 \001(\005\"\217" +
      "\001\n\005Offer\022\016\n\006source\030\001 \001(\t\022\021\n\trequestId\030\002 " +
      "\001(\t\022\n\n\002id\030\003 \001(\t\022\r\n\005price\030\004 \001(\001\022\016\n\006energy" +
      "\030\005 \001(\001\022(\n\004date\030\006 \001(\0132\032.google.protobuf.T" +
      "imestamp\022\016\n\006window\030\007 \001(\005\"5\n\014ForwardOffer" +
      "\022\016\n\006source\030\001 \001(\t\022\025\n\005offer\030\002 \001(\0132\006.Offer\"" +
      "-\n\013Reservation\022\017\n\007request\030\001 \001(\t\022\r\n\005offer" +
      "\030\002 \001(\t\"a\n\021ReservationAction\022!\n\013reservati" +
      "on\030\001 \001(\0132\014.Reservation\022\027\n\006action\030\002 \001(\0162\007" +
      ".Action\022\020\n\010argument\030\003 \001(\t\"N\n\030Reservation" +
      "PaymentOption\022!\n\013reservation\030\001 \001(\0132\014.Res" +
      "ervation\022\017\n\007options\030\002 \003(\t\"\370\001\n\007Message\022\033\n" +
      "\007request\030\001 \001(\0132\010.RequestH\000\022\027\n\005offer\030\002 \001(" +
      "\0132\006.OfferH\000\022%\n\014forwardOffer\030\003 \001(\0132\r.Forw" +
      "ardOfferH\000\022#\n\013reservation\030\004 \001(\0132\014.Reserv" +
      "ationH\000\022/\n\021reservationAction\030\005 \001(\0132\022.Res" +
      "ervationActionH\000\0223\n\016paymentOptions\030\006 \001(\013" +
      "2\031.ReservationPaymentOptionH\000B\005\n\003msg*)\n\006" +
      "Action\022\n\n\006ACCEPT\020\000\022\n\n\006REJECT\020\001\022\007\n\003PAY\020\002B" +
      "(\n\037org.beyene.protocol.tcp.messageB\003DtoP" +
      "\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.TimestampProto.getDescriptor(),
        }, assigner);
    internal_static_Request_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Request_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Request_descriptor,
        new java.lang.String[] { "Source", "Id", "Energy", "Date", "Window", });
    internal_static_Offer_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_Offer_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Offer_descriptor,
        new java.lang.String[] { "Source", "RequestId", "Id", "Price", "Energy", "Date", "Window", });
    internal_static_ForwardOffer_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_ForwardOffer_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ForwardOffer_descriptor,
        new java.lang.String[] { "Source", "Offer", });
    internal_static_Reservation_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_Reservation_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Reservation_descriptor,
        new java.lang.String[] { "Request", "Offer", });
    internal_static_ReservationAction_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_ReservationAction_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ReservationAction_descriptor,
        new java.lang.String[] { "Reservation", "Action", "Argument", });
    internal_static_ReservationPaymentOption_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_ReservationPaymentOption_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ReservationPaymentOption_descriptor,
        new java.lang.String[] { "Reservation", "Options", });
    internal_static_Message_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_Message_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Message_descriptor,
        new java.lang.String[] { "Request", "Offer", "ForwardOffer", "Reservation", "ReservationAction", "PaymentOptions", "Msg", });
    com.google.protobuf.TimestampProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
