// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dtos.proto

package org.beyene.protocol.tcp.message;

/**
 * Protobuf type {@code ForwardOffer}
 */
public  final class ForwardOffer extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:ForwardOffer)
    ForwardOfferOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ForwardOffer.newBuilder() to construct.
  private ForwardOffer(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ForwardOffer() {
    source_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private ForwardOffer(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            source_ = s;
            break;
          }
          case 18: {
            org.beyene.protocol.tcp.message.Offer.Builder subBuilder = null;
            if (offer_ != null) {
              subBuilder = offer_.toBuilder();
            }
            offer_ = input.readMessage(org.beyene.protocol.tcp.message.Offer.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(offer_);
              offer_ = subBuilder.buildPartial();
            }

            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.beyene.protocol.tcp.message.Dto.internal_static_ForwardOffer_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.beyene.protocol.tcp.message.Dto.internal_static_ForwardOffer_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.beyene.protocol.tcp.message.ForwardOffer.class, org.beyene.protocol.tcp.message.ForwardOffer.Builder.class);
  }

  public static final int SOURCE_FIELD_NUMBER = 1;
  private volatile java.lang.Object source_;
  /**
   * <code>string source = 1;</code>
   */
  public java.lang.String getSource() {
    java.lang.Object ref = source_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      source_ = s;
      return s;
    }
  }
  /**
   * <code>string source = 1;</code>
   */
  public com.google.protobuf.ByteString
      getSourceBytes() {
    java.lang.Object ref = source_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      source_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int OFFER_FIELD_NUMBER = 2;
  private org.beyene.protocol.tcp.message.Offer offer_;
  /**
   * <code>.Offer offer = 2;</code>
   */
  public boolean hasOffer() {
    return offer_ != null;
  }
  /**
   * <code>.Offer offer = 2;</code>
   */
  public org.beyene.protocol.tcp.message.Offer getOffer() {
    return offer_ == null ? org.beyene.protocol.tcp.message.Offer.getDefaultInstance() : offer_;
  }
  /**
   * <code>.Offer offer = 2;</code>
   */
  public org.beyene.protocol.tcp.message.OfferOrBuilder getOfferOrBuilder() {
    return getOffer();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getSourceBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, source_);
    }
    if (offer_ != null) {
      output.writeMessage(2, getOffer());
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getSourceBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, source_);
    }
    if (offer_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getOffer());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.beyene.protocol.tcp.message.ForwardOffer)) {
      return super.equals(obj);
    }
    org.beyene.protocol.tcp.message.ForwardOffer other = (org.beyene.protocol.tcp.message.ForwardOffer) obj;

    if (!getSource()
        .equals(other.getSource())) return false;
    if (hasOffer() != other.hasOffer()) return false;
    if (hasOffer()) {
      if (!getOffer()
          .equals(other.getOffer())) return false;
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + SOURCE_FIELD_NUMBER;
    hash = (53 * hash) + getSource().hashCode();
    if (hasOffer()) {
      hash = (37 * hash) + OFFER_FIELD_NUMBER;
      hash = (53 * hash) + getOffer().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.beyene.protocol.tcp.message.ForwardOffer parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.beyene.protocol.tcp.message.ForwardOffer parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.beyene.protocol.tcp.message.ForwardOffer parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.beyene.protocol.tcp.message.ForwardOffer parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.beyene.protocol.tcp.message.ForwardOffer parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.beyene.protocol.tcp.message.ForwardOffer parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.beyene.protocol.tcp.message.ForwardOffer parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.beyene.protocol.tcp.message.ForwardOffer parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.beyene.protocol.tcp.message.ForwardOffer parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static org.beyene.protocol.tcp.message.ForwardOffer parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.beyene.protocol.tcp.message.ForwardOffer parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.beyene.protocol.tcp.message.ForwardOffer parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.beyene.protocol.tcp.message.ForwardOffer prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code ForwardOffer}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:ForwardOffer)
      org.beyene.protocol.tcp.message.ForwardOfferOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.beyene.protocol.tcp.message.Dto.internal_static_ForwardOffer_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.beyene.protocol.tcp.message.Dto.internal_static_ForwardOffer_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.beyene.protocol.tcp.message.ForwardOffer.class, org.beyene.protocol.tcp.message.ForwardOffer.Builder.class);
    }

    // Construct using org.beyene.protocol.tcp.message.ForwardOffer.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      source_ = "";

      if (offerBuilder_ == null) {
        offer_ = null;
      } else {
        offer_ = null;
        offerBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.beyene.protocol.tcp.message.Dto.internal_static_ForwardOffer_descriptor;
    }

    @java.lang.Override
    public org.beyene.protocol.tcp.message.ForwardOffer getDefaultInstanceForType() {
      return org.beyene.protocol.tcp.message.ForwardOffer.getDefaultInstance();
    }

    @java.lang.Override
    public org.beyene.protocol.tcp.message.ForwardOffer build() {
      org.beyene.protocol.tcp.message.ForwardOffer result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public org.beyene.protocol.tcp.message.ForwardOffer buildPartial() {
      org.beyene.protocol.tcp.message.ForwardOffer result = new org.beyene.protocol.tcp.message.ForwardOffer(this);
      result.source_ = source_;
      if (offerBuilder_ == null) {
        result.offer_ = offer_;
      } else {
        result.offer_ = offerBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.beyene.protocol.tcp.message.ForwardOffer) {
        return mergeFrom((org.beyene.protocol.tcp.message.ForwardOffer)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.beyene.protocol.tcp.message.ForwardOffer other) {
      if (other == org.beyene.protocol.tcp.message.ForwardOffer.getDefaultInstance()) return this;
      if (!other.getSource().isEmpty()) {
        source_ = other.source_;
        onChanged();
      }
      if (other.hasOffer()) {
        mergeOffer(other.getOffer());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      org.beyene.protocol.tcp.message.ForwardOffer parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (org.beyene.protocol.tcp.message.ForwardOffer) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object source_ = "";
    /**
     * <code>string source = 1;</code>
     */
    public java.lang.String getSource() {
      java.lang.Object ref = source_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        source_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string source = 1;</code>
     */
    public com.google.protobuf.ByteString
        getSourceBytes() {
      java.lang.Object ref = source_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        source_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string source = 1;</code>
     */
    public Builder setSource(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      source_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string source = 1;</code>
     */
    public Builder clearSource() {
      
      source_ = getDefaultInstance().getSource();
      onChanged();
      return this;
    }
    /**
     * <code>string source = 1;</code>
     */
    public Builder setSourceBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      source_ = value;
      onChanged();
      return this;
    }

    private org.beyene.protocol.tcp.message.Offer offer_;
    private com.google.protobuf.SingleFieldBuilderV3<
        org.beyene.protocol.tcp.message.Offer, org.beyene.protocol.tcp.message.Offer.Builder, org.beyene.protocol.tcp.message.OfferOrBuilder> offerBuilder_;
    /**
     * <code>.Offer offer = 2;</code>
     */
    public boolean hasOffer() {
      return offerBuilder_ != null || offer_ != null;
    }
    /**
     * <code>.Offer offer = 2;</code>
     */
    public org.beyene.protocol.tcp.message.Offer getOffer() {
      if (offerBuilder_ == null) {
        return offer_ == null ? org.beyene.protocol.tcp.message.Offer.getDefaultInstance() : offer_;
      } else {
        return offerBuilder_.getMessage();
      }
    }
    /**
     * <code>.Offer offer = 2;</code>
     */
    public Builder setOffer(org.beyene.protocol.tcp.message.Offer value) {
      if (offerBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        offer_ = value;
        onChanged();
      } else {
        offerBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.Offer offer = 2;</code>
     */
    public Builder setOffer(
        org.beyene.protocol.tcp.message.Offer.Builder builderForValue) {
      if (offerBuilder_ == null) {
        offer_ = builderForValue.build();
        onChanged();
      } else {
        offerBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.Offer offer = 2;</code>
     */
    public Builder mergeOffer(org.beyene.protocol.tcp.message.Offer value) {
      if (offerBuilder_ == null) {
        if (offer_ != null) {
          offer_ =
            org.beyene.protocol.tcp.message.Offer.newBuilder(offer_).mergeFrom(value).buildPartial();
        } else {
          offer_ = value;
        }
        onChanged();
      } else {
        offerBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.Offer offer = 2;</code>
     */
    public Builder clearOffer() {
      if (offerBuilder_ == null) {
        offer_ = null;
        onChanged();
      } else {
        offer_ = null;
        offerBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.Offer offer = 2;</code>
     */
    public org.beyene.protocol.tcp.message.Offer.Builder getOfferBuilder() {
      
      onChanged();
      return getOfferFieldBuilder().getBuilder();
    }
    /**
     * <code>.Offer offer = 2;</code>
     */
    public org.beyene.protocol.tcp.message.OfferOrBuilder getOfferOrBuilder() {
      if (offerBuilder_ != null) {
        return offerBuilder_.getMessageOrBuilder();
      } else {
        return offer_ == null ?
            org.beyene.protocol.tcp.message.Offer.getDefaultInstance() : offer_;
      }
    }
    /**
     * <code>.Offer offer = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        org.beyene.protocol.tcp.message.Offer, org.beyene.protocol.tcp.message.Offer.Builder, org.beyene.protocol.tcp.message.OfferOrBuilder> 
        getOfferFieldBuilder() {
      if (offerBuilder_ == null) {
        offerBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            org.beyene.protocol.tcp.message.Offer, org.beyene.protocol.tcp.message.Offer.Builder, org.beyene.protocol.tcp.message.OfferOrBuilder>(
                getOffer(),
                getParentForChildren(),
                isClean());
        offer_ = null;
      }
      return offerBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:ForwardOffer)
  }

  // @@protoc_insertion_point(class_scope:ForwardOffer)
  private static final org.beyene.protocol.tcp.message.ForwardOffer DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.beyene.protocol.tcp.message.ForwardOffer();
  }

  public static org.beyene.protocol.tcp.message.ForwardOffer getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ForwardOffer>
      PARSER = new com.google.protobuf.AbstractParser<ForwardOffer>() {
    @java.lang.Override
    public ForwardOffer parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new ForwardOffer(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ForwardOffer> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ForwardOffer> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public org.beyene.protocol.tcp.message.ForwardOffer getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

