// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dtos.proto

package org.beyene.protocol.tcp.message;

public interface ForwardOfferOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ForwardOffer)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string source = 1;</code>
   */
  java.lang.String getSource();
  /**
   * <code>string source = 1;</code>
   */
  com.google.protobuf.ByteString
      getSourceBytes();

  /**
   * <code>.Offer offer = 2;</code>
   */
  boolean hasOffer();
  /**
   * <code>.Offer offer = 2;</code>
   */
  org.beyene.protocol.tcp.message.Offer getOffer();
  /**
   * <code>.Offer offer = 2;</code>
   */
  org.beyene.protocol.tcp.message.OfferOrBuilder getOfferOrBuilder();
}
