// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dtos.proto

package org.beyene.protocol.tcp.message;

/**
 * Protobuf type {@code Message}
 */
public  final class Message extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:Message)
    MessageOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Message.newBuilder() to construct.
  private Message(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Message() {
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private Message(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            org.beyene.protocol.tcp.message.Request.Builder subBuilder = null;
            if (msgCase_ == 1) {
              subBuilder = ((org.beyene.protocol.tcp.message.Request) msg_).toBuilder();
            }
            msg_ =
                input.readMessage(org.beyene.protocol.tcp.message.Request.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((org.beyene.protocol.tcp.message.Request) msg_);
              msg_ = subBuilder.buildPartial();
            }
            msgCase_ = 1;
            break;
          }
          case 18: {
            org.beyene.protocol.tcp.message.Offer.Builder subBuilder = null;
            if (msgCase_ == 2) {
              subBuilder = ((org.beyene.protocol.tcp.message.Offer) msg_).toBuilder();
            }
            msg_ =
                input.readMessage(org.beyene.protocol.tcp.message.Offer.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((org.beyene.protocol.tcp.message.Offer) msg_);
              msg_ = subBuilder.buildPartial();
            }
            msgCase_ = 2;
            break;
          }
          case 26: {
            org.beyene.protocol.tcp.message.ForwardOffer.Builder subBuilder = null;
            if (msgCase_ == 3) {
              subBuilder = ((org.beyene.protocol.tcp.message.ForwardOffer) msg_).toBuilder();
            }
            msg_ =
                input.readMessage(org.beyene.protocol.tcp.message.ForwardOffer.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((org.beyene.protocol.tcp.message.ForwardOffer) msg_);
              msg_ = subBuilder.buildPartial();
            }
            msgCase_ = 3;
            break;
          }
          case 34: {
            org.beyene.protocol.tcp.message.Reservation.Builder subBuilder = null;
            if (msgCase_ == 4) {
              subBuilder = ((org.beyene.protocol.tcp.message.Reservation) msg_).toBuilder();
            }
            msg_ =
                input.readMessage(org.beyene.protocol.tcp.message.Reservation.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((org.beyene.protocol.tcp.message.Reservation) msg_);
              msg_ = subBuilder.buildPartial();
            }
            msgCase_ = 4;
            break;
          }
          case 42: {
            org.beyene.protocol.tcp.message.ReservationAction.Builder subBuilder = null;
            if (msgCase_ == 5) {
              subBuilder = ((org.beyene.protocol.tcp.message.ReservationAction) msg_).toBuilder();
            }
            msg_ =
                input.readMessage(org.beyene.protocol.tcp.message.ReservationAction.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((org.beyene.protocol.tcp.message.ReservationAction) msg_);
              msg_ = subBuilder.buildPartial();
            }
            msgCase_ = 5;
            break;
          }
          case 50: {
            org.beyene.protocol.tcp.message.ReservationPaymentOption.Builder subBuilder = null;
            if (msgCase_ == 6) {
              subBuilder = ((org.beyene.protocol.tcp.message.ReservationPaymentOption) msg_).toBuilder();
            }
            msg_ =
                input.readMessage(org.beyene.protocol.tcp.message.ReservationPaymentOption.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((org.beyene.protocol.tcp.message.ReservationPaymentOption) msg_);
              msg_ = subBuilder.buildPartial();
            }
            msgCase_ = 6;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.beyene.protocol.tcp.message.Dto.internal_static_Message_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.beyene.protocol.tcp.message.Dto.internal_static_Message_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.beyene.protocol.tcp.message.Message.class, org.beyene.protocol.tcp.message.Message.Builder.class);
  }

  private int msgCase_ = 0;
  private java.lang.Object msg_;
  public enum MsgCase
      implements com.google.protobuf.Internal.EnumLite {
    REQUEST(1),
    OFFER(2),
    FORWARDOFFER(3),
    RESERVATION(4),
    RESERVATIONACTION(5),
    PAYMENTOPTIONS(6),
    MSG_NOT_SET(0);
    private final int value;
    private MsgCase(int value) {
      this.value = value;
    }
    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static MsgCase valueOf(int value) {
      return forNumber(value);
    }

    public static MsgCase forNumber(int value) {
      switch (value) {
        case 1: return REQUEST;
        case 2: return OFFER;
        case 3: return FORWARDOFFER;
        case 4: return RESERVATION;
        case 5: return RESERVATIONACTION;
        case 6: return PAYMENTOPTIONS;
        case 0: return MSG_NOT_SET;
        default: return null;
      }
    }
    public int getNumber() {
      return this.value;
    }
  };

  public MsgCase
  getMsgCase() {
    return MsgCase.forNumber(
        msgCase_);
  }

  public static final int REQUEST_FIELD_NUMBER = 1;
  /**
   * <code>.Request request = 1;</code>
   */
  public boolean hasRequest() {
    return msgCase_ == 1;
  }
  /**
   * <code>.Request request = 1;</code>
   */
  public org.beyene.protocol.tcp.message.Request getRequest() {
    if (msgCase_ == 1) {
       return (org.beyene.protocol.tcp.message.Request) msg_;
    }
    return org.beyene.protocol.tcp.message.Request.getDefaultInstance();
  }
  /**
   * <code>.Request request = 1;</code>
   */
  public org.beyene.protocol.tcp.message.RequestOrBuilder getRequestOrBuilder() {
    if (msgCase_ == 1) {
       return (org.beyene.protocol.tcp.message.Request) msg_;
    }
    return org.beyene.protocol.tcp.message.Request.getDefaultInstance();
  }

  public static final int OFFER_FIELD_NUMBER = 2;
  /**
   * <code>.Offer offer = 2;</code>
   */
  public boolean hasOffer() {
    return msgCase_ == 2;
  }
  /**
   * <code>.Offer offer = 2;</code>
   */
  public org.beyene.protocol.tcp.message.Offer getOffer() {
    if (msgCase_ == 2) {
       return (org.beyene.protocol.tcp.message.Offer) msg_;
    }
    return org.beyene.protocol.tcp.message.Offer.getDefaultInstance();
  }
  /**
   * <code>.Offer offer = 2;</code>
   */
  public org.beyene.protocol.tcp.message.OfferOrBuilder getOfferOrBuilder() {
    if (msgCase_ == 2) {
       return (org.beyene.protocol.tcp.message.Offer) msg_;
    }
    return org.beyene.protocol.tcp.message.Offer.getDefaultInstance();
  }

  public static final int FORWARDOFFER_FIELD_NUMBER = 3;
  /**
   * <code>.ForwardOffer forwardOffer = 3;</code>
   */
  public boolean hasForwardOffer() {
    return msgCase_ == 3;
  }
  /**
   * <code>.ForwardOffer forwardOffer = 3;</code>
   */
  public org.beyene.protocol.tcp.message.ForwardOffer getForwardOffer() {
    if (msgCase_ == 3) {
       return (org.beyene.protocol.tcp.message.ForwardOffer) msg_;
    }
    return org.beyene.protocol.tcp.message.ForwardOffer.getDefaultInstance();
  }
  /**
   * <code>.ForwardOffer forwardOffer = 3;</code>
   */
  public org.beyene.protocol.tcp.message.ForwardOfferOrBuilder getForwardOfferOrBuilder() {
    if (msgCase_ == 3) {
       return (org.beyene.protocol.tcp.message.ForwardOffer) msg_;
    }
    return org.beyene.protocol.tcp.message.ForwardOffer.getDefaultInstance();
  }

  public static final int RESERVATION_FIELD_NUMBER = 4;
  /**
   * <code>.Reservation reservation = 4;</code>
   */
  public boolean hasReservation() {
    return msgCase_ == 4;
  }
  /**
   * <code>.Reservation reservation = 4;</code>
   */
  public org.beyene.protocol.tcp.message.Reservation getReservation() {
    if (msgCase_ == 4) {
       return (org.beyene.protocol.tcp.message.Reservation) msg_;
    }
    return org.beyene.protocol.tcp.message.Reservation.getDefaultInstance();
  }
  /**
   * <code>.Reservation reservation = 4;</code>
   */
  public org.beyene.protocol.tcp.message.ReservationOrBuilder getReservationOrBuilder() {
    if (msgCase_ == 4) {
       return (org.beyene.protocol.tcp.message.Reservation) msg_;
    }
    return org.beyene.protocol.tcp.message.Reservation.getDefaultInstance();
  }

  public static final int RESERVATIONACTION_FIELD_NUMBER = 5;
  /**
   * <code>.ReservationAction reservationAction = 5;</code>
   */
  public boolean hasReservationAction() {
    return msgCase_ == 5;
  }
  /**
   * <code>.ReservationAction reservationAction = 5;</code>
   */
  public org.beyene.protocol.tcp.message.ReservationAction getReservationAction() {
    if (msgCase_ == 5) {
       return (org.beyene.protocol.tcp.message.ReservationAction) msg_;
    }
    return org.beyene.protocol.tcp.message.ReservationAction.getDefaultInstance();
  }
  /**
   * <code>.ReservationAction reservationAction = 5;</code>
   */
  public org.beyene.protocol.tcp.message.ReservationActionOrBuilder getReservationActionOrBuilder() {
    if (msgCase_ == 5) {
       return (org.beyene.protocol.tcp.message.ReservationAction) msg_;
    }
    return org.beyene.protocol.tcp.message.ReservationAction.getDefaultInstance();
  }

  public static final int PAYMENTOPTIONS_FIELD_NUMBER = 6;
  /**
   * <code>.ReservationPaymentOption paymentOptions = 6;</code>
   */
  public boolean hasPaymentOptions() {
    return msgCase_ == 6;
  }
  /**
   * <code>.ReservationPaymentOption paymentOptions = 6;</code>
   */
  public org.beyene.protocol.tcp.message.ReservationPaymentOption getPaymentOptions() {
    if (msgCase_ == 6) {
       return (org.beyene.protocol.tcp.message.ReservationPaymentOption) msg_;
    }
    return org.beyene.protocol.tcp.message.ReservationPaymentOption.getDefaultInstance();
  }
  /**
   * <code>.ReservationPaymentOption paymentOptions = 6;</code>
   */
  public org.beyene.protocol.tcp.message.ReservationPaymentOptionOrBuilder getPaymentOptionsOrBuilder() {
    if (msgCase_ == 6) {
       return (org.beyene.protocol.tcp.message.ReservationPaymentOption) msg_;
    }
    return org.beyene.protocol.tcp.message.ReservationPaymentOption.getDefaultInstance();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (msgCase_ == 1) {
      output.writeMessage(1, (org.beyene.protocol.tcp.message.Request) msg_);
    }
    if (msgCase_ == 2) {
      output.writeMessage(2, (org.beyene.protocol.tcp.message.Offer) msg_);
    }
    if (msgCase_ == 3) {
      output.writeMessage(3, (org.beyene.protocol.tcp.message.ForwardOffer) msg_);
    }
    if (msgCase_ == 4) {
      output.writeMessage(4, (org.beyene.protocol.tcp.message.Reservation) msg_);
    }
    if (msgCase_ == 5) {
      output.writeMessage(5, (org.beyene.protocol.tcp.message.ReservationAction) msg_);
    }
    if (msgCase_ == 6) {
      output.writeMessage(6, (org.beyene.protocol.tcp.message.ReservationPaymentOption) msg_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (msgCase_ == 1) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, (org.beyene.protocol.tcp.message.Request) msg_);
    }
    if (msgCase_ == 2) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, (org.beyene.protocol.tcp.message.Offer) msg_);
    }
    if (msgCase_ == 3) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, (org.beyene.protocol.tcp.message.ForwardOffer) msg_);
    }
    if (msgCase_ == 4) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, (org.beyene.protocol.tcp.message.Reservation) msg_);
    }
    if (msgCase_ == 5) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(5, (org.beyene.protocol.tcp.message.ReservationAction) msg_);
    }
    if (msgCase_ == 6) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(6, (org.beyene.protocol.tcp.message.ReservationPaymentOption) msg_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.beyene.protocol.tcp.message.Message)) {
      return super.equals(obj);
    }
    org.beyene.protocol.tcp.message.Message other = (org.beyene.protocol.tcp.message.Message) obj;

    if (!getMsgCase().equals(other.getMsgCase())) return false;
    switch (msgCase_) {
      case 1:
        if (!getRequest()
            .equals(other.getRequest())) return false;
        break;
      case 2:
        if (!getOffer()
            .equals(other.getOffer())) return false;
        break;
      case 3:
        if (!getForwardOffer()
            .equals(other.getForwardOffer())) return false;
        break;
      case 4:
        if (!getReservation()
            .equals(other.getReservation())) return false;
        break;
      case 5:
        if (!getReservationAction()
            .equals(other.getReservationAction())) return false;
        break;
      case 6:
        if (!getPaymentOptions()
            .equals(other.getPaymentOptions())) return false;
        break;
      case 0:
      default:
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    switch (msgCase_) {
      case 1:
        hash = (37 * hash) + REQUEST_FIELD_NUMBER;
        hash = (53 * hash) + getRequest().hashCode();
        break;
      case 2:
        hash = (37 * hash) + OFFER_FIELD_NUMBER;
        hash = (53 * hash) + getOffer().hashCode();
        break;
      case 3:
        hash = (37 * hash) + FORWARDOFFER_FIELD_NUMBER;
        hash = (53 * hash) + getForwardOffer().hashCode();
        break;
      case 4:
        hash = (37 * hash) + RESERVATION_FIELD_NUMBER;
        hash = (53 * hash) + getReservation().hashCode();
        break;
      case 5:
        hash = (37 * hash) + RESERVATIONACTION_FIELD_NUMBER;
        hash = (53 * hash) + getReservationAction().hashCode();
        break;
      case 6:
        hash = (37 * hash) + PAYMENTOPTIONS_FIELD_NUMBER;
        hash = (53 * hash) + getPaymentOptions().hashCode();
        break;
      case 0:
      default:
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.beyene.protocol.tcp.message.Message parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.beyene.protocol.tcp.message.Message parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.beyene.protocol.tcp.message.Message parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.beyene.protocol.tcp.message.Message parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.beyene.protocol.tcp.message.Message parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.beyene.protocol.tcp.message.Message parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.beyene.protocol.tcp.message.Message parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.beyene.protocol.tcp.message.Message parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.beyene.protocol.tcp.message.Message parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static org.beyene.protocol.tcp.message.Message parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.beyene.protocol.tcp.message.Message parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.beyene.protocol.tcp.message.Message parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.beyene.protocol.tcp.message.Message prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code Message}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:Message)
      org.beyene.protocol.tcp.message.MessageOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.beyene.protocol.tcp.message.Dto.internal_static_Message_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.beyene.protocol.tcp.message.Dto.internal_static_Message_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.beyene.protocol.tcp.message.Message.class, org.beyene.protocol.tcp.message.Message.Builder.class);
    }

    // Construct using org.beyene.protocol.tcp.message.Message.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      msgCase_ = 0;
      msg_ = null;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.beyene.protocol.tcp.message.Dto.internal_static_Message_descriptor;
    }

    @java.lang.Override
    public org.beyene.protocol.tcp.message.Message getDefaultInstanceForType() {
      return org.beyene.protocol.tcp.message.Message.getDefaultInstance();
    }

    @java.lang.Override
    public org.beyene.protocol.tcp.message.Message build() {
      org.beyene.protocol.tcp.message.Message result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public org.beyene.protocol.tcp.message.Message buildPartial() {
      org.beyene.protocol.tcp.message.Message result = new org.beyene.protocol.tcp.message.Message(this);
      if (msgCase_ == 1) {
        if (requestBuilder_ == null) {
          result.msg_ = msg_;
        } else {
          result.msg_ = requestBuilder_.build();
        }
      }
      if (msgCase_ == 2) {
        if (offerBuilder_ == null) {
          result.msg_ = msg_;
        } else {
          result.msg_ = offerBuilder_.build();
        }
      }
      if (msgCase_ == 3) {
        if (forwardOfferBuilder_ == null) {
          result.msg_ = msg_;
        } else {
          result.msg_ = forwardOfferBuilder_.build();
        }
      }
      if (msgCase_ == 4) {
        if (reservationBuilder_ == null) {
          result.msg_ = msg_;
        } else {
          result.msg_ = reservationBuilder_.build();
        }
      }
      if (msgCase_ == 5) {
        if (reservationActionBuilder_ == null) {
          result.msg_ = msg_;
        } else {
          result.msg_ = reservationActionBuilder_.build();
        }
      }
      if (msgCase_ == 6) {
        if (paymentOptionsBuilder_ == null) {
          result.msg_ = msg_;
        } else {
          result.msg_ = paymentOptionsBuilder_.build();
        }
      }
      result.msgCase_ = msgCase_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.beyene.protocol.tcp.message.Message) {
        return mergeFrom((org.beyene.protocol.tcp.message.Message)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.beyene.protocol.tcp.message.Message other) {
      if (other == org.beyene.protocol.tcp.message.Message.getDefaultInstance()) return this;
      switch (other.getMsgCase()) {
        case REQUEST: {
          mergeRequest(other.getRequest());
          break;
        }
        case OFFER: {
          mergeOffer(other.getOffer());
          break;
        }
        case FORWARDOFFER: {
          mergeForwardOffer(other.getForwardOffer());
          break;
        }
        case RESERVATION: {
          mergeReservation(other.getReservation());
          break;
        }
        case RESERVATIONACTION: {
          mergeReservationAction(other.getReservationAction());
          break;
        }
        case PAYMENTOPTIONS: {
          mergePaymentOptions(other.getPaymentOptions());
          break;
        }
        case MSG_NOT_SET: {
          break;
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      org.beyene.protocol.tcp.message.Message parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (org.beyene.protocol.tcp.message.Message) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int msgCase_ = 0;
    private java.lang.Object msg_;
    public MsgCase
        getMsgCase() {
      return MsgCase.forNumber(
          msgCase_);
    }

    public Builder clearMsg() {
      msgCase_ = 0;
      msg_ = null;
      onChanged();
      return this;
    }


    private com.google.protobuf.SingleFieldBuilderV3<
        org.beyene.protocol.tcp.message.Request, org.beyene.protocol.tcp.message.Request.Builder, org.beyene.protocol.tcp.message.RequestOrBuilder> requestBuilder_;
    /**
     * <code>.Request request = 1;</code>
     */
    public boolean hasRequest() {
      return msgCase_ == 1;
    }
    /**
     * <code>.Request request = 1;</code>
     */
    public org.beyene.protocol.tcp.message.Request getRequest() {
      if (requestBuilder_ == null) {
        if (msgCase_ == 1) {
          return (org.beyene.protocol.tcp.message.Request) msg_;
        }
        return org.beyene.protocol.tcp.message.Request.getDefaultInstance();
      } else {
        if (msgCase_ == 1) {
          return requestBuilder_.getMessage();
        }
        return org.beyene.protocol.tcp.message.Request.getDefaultInstance();
      }
    }
    /**
     * <code>.Request request = 1;</code>
     */
    public Builder setRequest(org.beyene.protocol.tcp.message.Request value) {
      if (requestBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        msg_ = value;
        onChanged();
      } else {
        requestBuilder_.setMessage(value);
      }
      msgCase_ = 1;
      return this;
    }
    /**
     * <code>.Request request = 1;</code>
     */
    public Builder setRequest(
        org.beyene.protocol.tcp.message.Request.Builder builderForValue) {
      if (requestBuilder_ == null) {
        msg_ = builderForValue.build();
        onChanged();
      } else {
        requestBuilder_.setMessage(builderForValue.build());
      }
      msgCase_ = 1;
      return this;
    }
    /**
     * <code>.Request request = 1;</code>
     */
    public Builder mergeRequest(org.beyene.protocol.tcp.message.Request value) {
      if (requestBuilder_ == null) {
        if (msgCase_ == 1 &&
            msg_ != org.beyene.protocol.tcp.message.Request.getDefaultInstance()) {
          msg_ = org.beyene.protocol.tcp.message.Request.newBuilder((org.beyene.protocol.tcp.message.Request) msg_)
              .mergeFrom(value).buildPartial();
        } else {
          msg_ = value;
        }
        onChanged();
      } else {
        if (msgCase_ == 1) {
          requestBuilder_.mergeFrom(value);
        }
        requestBuilder_.setMessage(value);
      }
      msgCase_ = 1;
      return this;
    }
    /**
     * <code>.Request request = 1;</code>
     */
    public Builder clearRequest() {
      if (requestBuilder_ == null) {
        if (msgCase_ == 1) {
          msgCase_ = 0;
          msg_ = null;
          onChanged();
        }
      } else {
        if (msgCase_ == 1) {
          msgCase_ = 0;
          msg_ = null;
        }
        requestBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.Request request = 1;</code>
     */
    public org.beyene.protocol.tcp.message.Request.Builder getRequestBuilder() {
      return getRequestFieldBuilder().getBuilder();
    }
    /**
     * <code>.Request request = 1;</code>
     */
    public org.beyene.protocol.tcp.message.RequestOrBuilder getRequestOrBuilder() {
      if ((msgCase_ == 1) && (requestBuilder_ != null)) {
        return requestBuilder_.getMessageOrBuilder();
      } else {
        if (msgCase_ == 1) {
          return (org.beyene.protocol.tcp.message.Request) msg_;
        }
        return org.beyene.protocol.tcp.message.Request.getDefaultInstance();
      }
    }
    /**
     * <code>.Request request = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        org.beyene.protocol.tcp.message.Request, org.beyene.protocol.tcp.message.Request.Builder, org.beyene.protocol.tcp.message.RequestOrBuilder> 
        getRequestFieldBuilder() {
      if (requestBuilder_ == null) {
        if (!(msgCase_ == 1)) {
          msg_ = org.beyene.protocol.tcp.message.Request.getDefaultInstance();
        }
        requestBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            org.beyene.protocol.tcp.message.Request, org.beyene.protocol.tcp.message.Request.Builder, org.beyene.protocol.tcp.message.RequestOrBuilder>(
                (org.beyene.protocol.tcp.message.Request) msg_,
                getParentForChildren(),
                isClean());
        msg_ = null;
      }
      msgCase_ = 1;
      onChanged();;
      return requestBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        org.beyene.protocol.tcp.message.Offer, org.beyene.protocol.tcp.message.Offer.Builder, org.beyene.protocol.tcp.message.OfferOrBuilder> offerBuilder_;
    /**
     * <code>.Offer offer = 2;</code>
     */
    public boolean hasOffer() {
      return msgCase_ == 2;
    }
    /**
     * <code>.Offer offer = 2;</code>
     */
    public org.beyene.protocol.tcp.message.Offer getOffer() {
      if (offerBuilder_ == null) {
        if (msgCase_ == 2) {
          return (org.beyene.protocol.tcp.message.Offer) msg_;
        }
        return org.beyene.protocol.tcp.message.Offer.getDefaultInstance();
      } else {
        if (msgCase_ == 2) {
          return offerBuilder_.getMessage();
        }
        return org.beyene.protocol.tcp.message.Offer.getDefaultInstance();
      }
    }
    /**
     * <code>.Offer offer = 2;</code>
     */
    public Builder setOffer(org.beyene.protocol.tcp.message.Offer value) {
      if (offerBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        msg_ = value;
        onChanged();
      } else {
        offerBuilder_.setMessage(value);
      }
      msgCase_ = 2;
      return this;
    }
    /**
     * <code>.Offer offer = 2;</code>
     */
    public Builder setOffer(
        org.beyene.protocol.tcp.message.Offer.Builder builderForValue) {
      if (offerBuilder_ == null) {
        msg_ = builderForValue.build();
        onChanged();
      } else {
        offerBuilder_.setMessage(builderForValue.build());
      }
      msgCase_ = 2;
      return this;
    }
    /**
     * <code>.Offer offer = 2;</code>
     */
    public Builder mergeOffer(org.beyene.protocol.tcp.message.Offer value) {
      if (offerBuilder_ == null) {
        if (msgCase_ == 2 &&
            msg_ != org.beyene.protocol.tcp.message.Offer.getDefaultInstance()) {
          msg_ = org.beyene.protocol.tcp.message.Offer.newBuilder((org.beyene.protocol.tcp.message.Offer) msg_)
              .mergeFrom(value).buildPartial();
        } else {
          msg_ = value;
        }
        onChanged();
      } else {
        if (msgCase_ == 2) {
          offerBuilder_.mergeFrom(value);
        }
        offerBuilder_.setMessage(value);
      }
      msgCase_ = 2;
      return this;
    }
    /**
     * <code>.Offer offer = 2;</code>
     */
    public Builder clearOffer() {
      if (offerBuilder_ == null) {
        if (msgCase_ == 2) {
          msgCase_ = 0;
          msg_ = null;
          onChanged();
        }
      } else {
        if (msgCase_ == 2) {
          msgCase_ = 0;
          msg_ = null;
        }
        offerBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.Offer offer = 2;</code>
     */
    public org.beyene.protocol.tcp.message.Offer.Builder getOfferBuilder() {
      return getOfferFieldBuilder().getBuilder();
    }
    /**
     * <code>.Offer offer = 2;</code>
     */
    public org.beyene.protocol.tcp.message.OfferOrBuilder getOfferOrBuilder() {
      if ((msgCase_ == 2) && (offerBuilder_ != null)) {
        return offerBuilder_.getMessageOrBuilder();
      } else {
        if (msgCase_ == 2) {
          return (org.beyene.protocol.tcp.message.Offer) msg_;
        }
        return org.beyene.protocol.tcp.message.Offer.getDefaultInstance();
      }
    }
    /**
     * <code>.Offer offer = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        org.beyene.protocol.tcp.message.Offer, org.beyene.protocol.tcp.message.Offer.Builder, org.beyene.protocol.tcp.message.OfferOrBuilder> 
        getOfferFieldBuilder() {
      if (offerBuilder_ == null) {
        if (!(msgCase_ == 2)) {
          msg_ = org.beyene.protocol.tcp.message.Offer.getDefaultInstance();
        }
        offerBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            org.beyene.protocol.tcp.message.Offer, org.beyene.protocol.tcp.message.Offer.Builder, org.beyene.protocol.tcp.message.OfferOrBuilder>(
                (org.beyene.protocol.tcp.message.Offer) msg_,
                getParentForChildren(),
                isClean());
        msg_ = null;
      }
      msgCase_ = 2;
      onChanged();;
      return offerBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        org.beyene.protocol.tcp.message.ForwardOffer, org.beyene.protocol.tcp.message.ForwardOffer.Builder, org.beyene.protocol.tcp.message.ForwardOfferOrBuilder> forwardOfferBuilder_;
    /**
     * <code>.ForwardOffer forwardOffer = 3;</code>
     */
    public boolean hasForwardOffer() {
      return msgCase_ == 3;
    }
    /**
     * <code>.ForwardOffer forwardOffer = 3;</code>
     */
    public org.beyene.protocol.tcp.message.ForwardOffer getForwardOffer() {
      if (forwardOfferBuilder_ == null) {
        if (msgCase_ == 3) {
          return (org.beyene.protocol.tcp.message.ForwardOffer) msg_;
        }
        return org.beyene.protocol.tcp.message.ForwardOffer.getDefaultInstance();
      } else {
        if (msgCase_ == 3) {
          return forwardOfferBuilder_.getMessage();
        }
        return org.beyene.protocol.tcp.message.ForwardOffer.getDefaultInstance();
      }
    }
    /**
     * <code>.ForwardOffer forwardOffer = 3;</code>
     */
    public Builder setForwardOffer(org.beyene.protocol.tcp.message.ForwardOffer value) {
      if (forwardOfferBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        msg_ = value;
        onChanged();
      } else {
        forwardOfferBuilder_.setMessage(value);
      }
      msgCase_ = 3;
      return this;
    }
    /**
     * <code>.ForwardOffer forwardOffer = 3;</code>
     */
    public Builder setForwardOffer(
        org.beyene.protocol.tcp.message.ForwardOffer.Builder builderForValue) {
      if (forwardOfferBuilder_ == null) {
        msg_ = builderForValue.build();
        onChanged();
      } else {
        forwardOfferBuilder_.setMessage(builderForValue.build());
      }
      msgCase_ = 3;
      return this;
    }
    /**
     * <code>.ForwardOffer forwardOffer = 3;</code>
     */
    public Builder mergeForwardOffer(org.beyene.protocol.tcp.message.ForwardOffer value) {
      if (forwardOfferBuilder_ == null) {
        if (msgCase_ == 3 &&
            msg_ != org.beyene.protocol.tcp.message.ForwardOffer.getDefaultInstance()) {
          msg_ = org.beyene.protocol.tcp.message.ForwardOffer.newBuilder((org.beyene.protocol.tcp.message.ForwardOffer) msg_)
              .mergeFrom(value).buildPartial();
        } else {
          msg_ = value;
        }
        onChanged();
      } else {
        if (msgCase_ == 3) {
          forwardOfferBuilder_.mergeFrom(value);
        }
        forwardOfferBuilder_.setMessage(value);
      }
      msgCase_ = 3;
      return this;
    }
    /**
     * <code>.ForwardOffer forwardOffer = 3;</code>
     */
    public Builder clearForwardOffer() {
      if (forwardOfferBuilder_ == null) {
        if (msgCase_ == 3) {
          msgCase_ = 0;
          msg_ = null;
          onChanged();
        }
      } else {
        if (msgCase_ == 3) {
          msgCase_ = 0;
          msg_ = null;
        }
        forwardOfferBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.ForwardOffer forwardOffer = 3;</code>
     */
    public org.beyene.protocol.tcp.message.ForwardOffer.Builder getForwardOfferBuilder() {
      return getForwardOfferFieldBuilder().getBuilder();
    }
    /**
     * <code>.ForwardOffer forwardOffer = 3;</code>
     */
    public org.beyene.protocol.tcp.message.ForwardOfferOrBuilder getForwardOfferOrBuilder() {
      if ((msgCase_ == 3) && (forwardOfferBuilder_ != null)) {
        return forwardOfferBuilder_.getMessageOrBuilder();
      } else {
        if (msgCase_ == 3) {
          return (org.beyene.protocol.tcp.message.ForwardOffer) msg_;
        }
        return org.beyene.protocol.tcp.message.ForwardOffer.getDefaultInstance();
      }
    }
    /**
     * <code>.ForwardOffer forwardOffer = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        org.beyene.protocol.tcp.message.ForwardOffer, org.beyene.protocol.tcp.message.ForwardOffer.Builder, org.beyene.protocol.tcp.message.ForwardOfferOrBuilder> 
        getForwardOfferFieldBuilder() {
      if (forwardOfferBuilder_ == null) {
        if (!(msgCase_ == 3)) {
          msg_ = org.beyene.protocol.tcp.message.ForwardOffer.getDefaultInstance();
        }
        forwardOfferBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            org.beyene.protocol.tcp.message.ForwardOffer, org.beyene.protocol.tcp.message.ForwardOffer.Builder, org.beyene.protocol.tcp.message.ForwardOfferOrBuilder>(
                (org.beyene.protocol.tcp.message.ForwardOffer) msg_,
                getParentForChildren(),
                isClean());
        msg_ = null;
      }
      msgCase_ = 3;
      onChanged();;
      return forwardOfferBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        org.beyene.protocol.tcp.message.Reservation, org.beyene.protocol.tcp.message.Reservation.Builder, org.beyene.protocol.tcp.message.ReservationOrBuilder> reservationBuilder_;
    /**
     * <code>.Reservation reservation = 4;</code>
     */
    public boolean hasReservation() {
      return msgCase_ == 4;
    }
    /**
     * <code>.Reservation reservation = 4;</code>
     */
    public org.beyene.protocol.tcp.message.Reservation getReservation() {
      if (reservationBuilder_ == null) {
        if (msgCase_ == 4) {
          return (org.beyene.protocol.tcp.message.Reservation) msg_;
        }
        return org.beyene.protocol.tcp.message.Reservation.getDefaultInstance();
      } else {
        if (msgCase_ == 4) {
          return reservationBuilder_.getMessage();
        }
        return org.beyene.protocol.tcp.message.Reservation.getDefaultInstance();
      }
    }
    /**
     * <code>.Reservation reservation = 4;</code>
     */
    public Builder setReservation(org.beyene.protocol.tcp.message.Reservation value) {
      if (reservationBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        msg_ = value;
        onChanged();
      } else {
        reservationBuilder_.setMessage(value);
      }
      msgCase_ = 4;
      return this;
    }
    /**
     * <code>.Reservation reservation = 4;</code>
     */
    public Builder setReservation(
        org.beyene.protocol.tcp.message.Reservation.Builder builderForValue) {
      if (reservationBuilder_ == null) {
        msg_ = builderForValue.build();
        onChanged();
      } else {
        reservationBuilder_.setMessage(builderForValue.build());
      }
      msgCase_ = 4;
      return this;
    }
    /**
     * <code>.Reservation reservation = 4;</code>
     */
    public Builder mergeReservation(org.beyene.protocol.tcp.message.Reservation value) {
      if (reservationBuilder_ == null) {
        if (msgCase_ == 4 &&
            msg_ != org.beyene.protocol.tcp.message.Reservation.getDefaultInstance()) {
          msg_ = org.beyene.protocol.tcp.message.Reservation.newBuilder((org.beyene.protocol.tcp.message.Reservation) msg_)
              .mergeFrom(value).buildPartial();
        } else {
          msg_ = value;
        }
        onChanged();
      } else {
        if (msgCase_ == 4) {
          reservationBuilder_.mergeFrom(value);
        }
        reservationBuilder_.setMessage(value);
      }
      msgCase_ = 4;
      return this;
    }
    /**
     * <code>.Reservation reservation = 4;</code>
     */
    public Builder clearReservation() {
      if (reservationBuilder_ == null) {
        if (msgCase_ == 4) {
          msgCase_ = 0;
          msg_ = null;
          onChanged();
        }
      } else {
        if (msgCase_ == 4) {
          msgCase_ = 0;
          msg_ = null;
        }
        reservationBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.Reservation reservation = 4;</code>
     */
    public org.beyene.protocol.tcp.message.Reservation.Builder getReservationBuilder() {
      return getReservationFieldBuilder().getBuilder();
    }
    /**
     * <code>.Reservation reservation = 4;</code>
     */
    public org.beyene.protocol.tcp.message.ReservationOrBuilder getReservationOrBuilder() {
      if ((msgCase_ == 4) && (reservationBuilder_ != null)) {
        return reservationBuilder_.getMessageOrBuilder();
      } else {
        if (msgCase_ == 4) {
          return (org.beyene.protocol.tcp.message.Reservation) msg_;
        }
        return org.beyene.protocol.tcp.message.Reservation.getDefaultInstance();
      }
    }
    /**
     * <code>.Reservation reservation = 4;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        org.beyene.protocol.tcp.message.Reservation, org.beyene.protocol.tcp.message.Reservation.Builder, org.beyene.protocol.tcp.message.ReservationOrBuilder> 
        getReservationFieldBuilder() {
      if (reservationBuilder_ == null) {
        if (!(msgCase_ == 4)) {
          msg_ = org.beyene.protocol.tcp.message.Reservation.getDefaultInstance();
        }
        reservationBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            org.beyene.protocol.tcp.message.Reservation, org.beyene.protocol.tcp.message.Reservation.Builder, org.beyene.protocol.tcp.message.ReservationOrBuilder>(
                (org.beyene.protocol.tcp.message.Reservation) msg_,
                getParentForChildren(),
                isClean());
        msg_ = null;
      }
      msgCase_ = 4;
      onChanged();;
      return reservationBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        org.beyene.protocol.tcp.message.ReservationAction, org.beyene.protocol.tcp.message.ReservationAction.Builder, org.beyene.protocol.tcp.message.ReservationActionOrBuilder> reservationActionBuilder_;
    /**
     * <code>.ReservationAction reservationAction = 5;</code>
     */
    public boolean hasReservationAction() {
      return msgCase_ == 5;
    }
    /**
     * <code>.ReservationAction reservationAction = 5;</code>
     */
    public org.beyene.protocol.tcp.message.ReservationAction getReservationAction() {
      if (reservationActionBuilder_ == null) {
        if (msgCase_ == 5) {
          return (org.beyene.protocol.tcp.message.ReservationAction) msg_;
        }
        return org.beyene.protocol.tcp.message.ReservationAction.getDefaultInstance();
      } else {
        if (msgCase_ == 5) {
          return reservationActionBuilder_.getMessage();
        }
        return org.beyene.protocol.tcp.message.ReservationAction.getDefaultInstance();
      }
    }
    /**
     * <code>.ReservationAction reservationAction = 5;</code>
     */
    public Builder setReservationAction(org.beyene.protocol.tcp.message.ReservationAction value) {
      if (reservationActionBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        msg_ = value;
        onChanged();
      } else {
        reservationActionBuilder_.setMessage(value);
      }
      msgCase_ = 5;
      return this;
    }
    /**
     * <code>.ReservationAction reservationAction = 5;</code>
     */
    public Builder setReservationAction(
        org.beyene.protocol.tcp.message.ReservationAction.Builder builderForValue) {
      if (reservationActionBuilder_ == null) {
        msg_ = builderForValue.build();
        onChanged();
      } else {
        reservationActionBuilder_.setMessage(builderForValue.build());
      }
      msgCase_ = 5;
      return this;
    }
    /**
     * <code>.ReservationAction reservationAction = 5;</code>
     */
    public Builder mergeReservationAction(org.beyene.protocol.tcp.message.ReservationAction value) {
      if (reservationActionBuilder_ == null) {
        if (msgCase_ == 5 &&
            msg_ != org.beyene.protocol.tcp.message.ReservationAction.getDefaultInstance()) {
          msg_ = org.beyene.protocol.tcp.message.ReservationAction.newBuilder((org.beyene.protocol.tcp.message.ReservationAction) msg_)
              .mergeFrom(value).buildPartial();
        } else {
          msg_ = value;
        }
        onChanged();
      } else {
        if (msgCase_ == 5) {
          reservationActionBuilder_.mergeFrom(value);
        }
        reservationActionBuilder_.setMessage(value);
      }
      msgCase_ = 5;
      return this;
    }
    /**
     * <code>.ReservationAction reservationAction = 5;</code>
     */
    public Builder clearReservationAction() {
      if (reservationActionBuilder_ == null) {
        if (msgCase_ == 5) {
          msgCase_ = 0;
          msg_ = null;
          onChanged();
        }
      } else {
        if (msgCase_ == 5) {
          msgCase_ = 0;
          msg_ = null;
        }
        reservationActionBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.ReservationAction reservationAction = 5;</code>
     */
    public org.beyene.protocol.tcp.message.ReservationAction.Builder getReservationActionBuilder() {
      return getReservationActionFieldBuilder().getBuilder();
    }
    /**
     * <code>.ReservationAction reservationAction = 5;</code>
     */
    public org.beyene.protocol.tcp.message.ReservationActionOrBuilder getReservationActionOrBuilder() {
      if ((msgCase_ == 5) && (reservationActionBuilder_ != null)) {
        return reservationActionBuilder_.getMessageOrBuilder();
      } else {
        if (msgCase_ == 5) {
          return (org.beyene.protocol.tcp.message.ReservationAction) msg_;
        }
        return org.beyene.protocol.tcp.message.ReservationAction.getDefaultInstance();
      }
    }
    /**
     * <code>.ReservationAction reservationAction = 5;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        org.beyene.protocol.tcp.message.ReservationAction, org.beyene.protocol.tcp.message.ReservationAction.Builder, org.beyene.protocol.tcp.message.ReservationActionOrBuilder> 
        getReservationActionFieldBuilder() {
      if (reservationActionBuilder_ == null) {
        if (!(msgCase_ == 5)) {
          msg_ = org.beyene.protocol.tcp.message.ReservationAction.getDefaultInstance();
        }
        reservationActionBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            org.beyene.protocol.tcp.message.ReservationAction, org.beyene.protocol.tcp.message.ReservationAction.Builder, org.beyene.protocol.tcp.message.ReservationActionOrBuilder>(
                (org.beyene.protocol.tcp.message.ReservationAction) msg_,
                getParentForChildren(),
                isClean());
        msg_ = null;
      }
      msgCase_ = 5;
      onChanged();;
      return reservationActionBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        org.beyene.protocol.tcp.message.ReservationPaymentOption, org.beyene.protocol.tcp.message.ReservationPaymentOption.Builder, org.beyene.protocol.tcp.message.ReservationPaymentOptionOrBuilder> paymentOptionsBuilder_;
    /**
     * <code>.ReservationPaymentOption paymentOptions = 6;</code>
     */
    public boolean hasPaymentOptions() {
      return msgCase_ == 6;
    }
    /**
     * <code>.ReservationPaymentOption paymentOptions = 6;</code>
     */
    public org.beyene.protocol.tcp.message.ReservationPaymentOption getPaymentOptions() {
      if (paymentOptionsBuilder_ == null) {
        if (msgCase_ == 6) {
          return (org.beyene.protocol.tcp.message.ReservationPaymentOption) msg_;
        }
        return org.beyene.protocol.tcp.message.ReservationPaymentOption.getDefaultInstance();
      } else {
        if (msgCase_ == 6) {
          return paymentOptionsBuilder_.getMessage();
        }
        return org.beyene.protocol.tcp.message.ReservationPaymentOption.getDefaultInstance();
      }
    }
    /**
     * <code>.ReservationPaymentOption paymentOptions = 6;</code>
     */
    public Builder setPaymentOptions(org.beyene.protocol.tcp.message.ReservationPaymentOption value) {
      if (paymentOptionsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        msg_ = value;
        onChanged();
      } else {
        paymentOptionsBuilder_.setMessage(value);
      }
      msgCase_ = 6;
      return this;
    }
    /**
     * <code>.ReservationPaymentOption paymentOptions = 6;</code>
     */
    public Builder setPaymentOptions(
        org.beyene.protocol.tcp.message.ReservationPaymentOption.Builder builderForValue) {
      if (paymentOptionsBuilder_ == null) {
        msg_ = builderForValue.build();
        onChanged();
      } else {
        paymentOptionsBuilder_.setMessage(builderForValue.build());
      }
      msgCase_ = 6;
      return this;
    }
    /**
     * <code>.ReservationPaymentOption paymentOptions = 6;</code>
     */
    public Builder mergePaymentOptions(org.beyene.protocol.tcp.message.ReservationPaymentOption value) {
      if (paymentOptionsBuilder_ == null) {
        if (msgCase_ == 6 &&
            msg_ != org.beyene.protocol.tcp.message.ReservationPaymentOption.getDefaultInstance()) {
          msg_ = org.beyene.protocol.tcp.message.ReservationPaymentOption.newBuilder((org.beyene.protocol.tcp.message.ReservationPaymentOption) msg_)
              .mergeFrom(value).buildPartial();
        } else {
          msg_ = value;
        }
        onChanged();
      } else {
        if (msgCase_ == 6) {
          paymentOptionsBuilder_.mergeFrom(value);
        }
        paymentOptionsBuilder_.setMessage(value);
      }
      msgCase_ = 6;
      return this;
    }
    /**
     * <code>.ReservationPaymentOption paymentOptions = 6;</code>
     */
    public Builder clearPaymentOptions() {
      if (paymentOptionsBuilder_ == null) {
        if (msgCase_ == 6) {
          msgCase_ = 0;
          msg_ = null;
          onChanged();
        }
      } else {
        if (msgCase_ == 6) {
          msgCase_ = 0;
          msg_ = null;
        }
        paymentOptionsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.ReservationPaymentOption paymentOptions = 6;</code>
     */
    public org.beyene.protocol.tcp.message.ReservationPaymentOption.Builder getPaymentOptionsBuilder() {
      return getPaymentOptionsFieldBuilder().getBuilder();
    }
    /**
     * <code>.ReservationPaymentOption paymentOptions = 6;</code>
     */
    public org.beyene.protocol.tcp.message.ReservationPaymentOptionOrBuilder getPaymentOptionsOrBuilder() {
      if ((msgCase_ == 6) && (paymentOptionsBuilder_ != null)) {
        return paymentOptionsBuilder_.getMessageOrBuilder();
      } else {
        if (msgCase_ == 6) {
          return (org.beyene.protocol.tcp.message.ReservationPaymentOption) msg_;
        }
        return org.beyene.protocol.tcp.message.ReservationPaymentOption.getDefaultInstance();
      }
    }
    /**
     * <code>.ReservationPaymentOption paymentOptions = 6;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        org.beyene.protocol.tcp.message.ReservationPaymentOption, org.beyene.protocol.tcp.message.ReservationPaymentOption.Builder, org.beyene.protocol.tcp.message.ReservationPaymentOptionOrBuilder> 
        getPaymentOptionsFieldBuilder() {
      if (paymentOptionsBuilder_ == null) {
        if (!(msgCase_ == 6)) {
          msg_ = org.beyene.protocol.tcp.message.ReservationPaymentOption.getDefaultInstance();
        }
        paymentOptionsBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            org.beyene.protocol.tcp.message.ReservationPaymentOption, org.beyene.protocol.tcp.message.ReservationPaymentOption.Builder, org.beyene.protocol.tcp.message.ReservationPaymentOptionOrBuilder>(
                (org.beyene.protocol.tcp.message.ReservationPaymentOption) msg_,
                getParentForChildren(),
                isClean());
        msg_ = null;
      }
      msgCase_ = 6;
      onChanged();;
      return paymentOptionsBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:Message)
  }

  // @@protoc_insertion_point(class_scope:Message)
  private static final org.beyene.protocol.tcp.message.Message DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.beyene.protocol.tcp.message.Message();
  }

  public static org.beyene.protocol.tcp.message.Message getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Message>
      PARSER = new com.google.protobuf.AbstractParser<Message>() {
    @java.lang.Override
    public Message parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new Message(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Message> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Message> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public org.beyene.protocol.tcp.message.Message getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

