// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dtos.proto

package org.beyene.protocol.tcp.message;

public interface MessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Message)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.Request request = 1;</code>
   */
  boolean hasRequest();
  /**
   * <code>.Request request = 1;</code>
   */
  org.beyene.protocol.tcp.message.Request getRequest();
  /**
   * <code>.Request request = 1;</code>
   */
  org.beyene.protocol.tcp.message.RequestOrBuilder getRequestOrBuilder();

  /**
   * <code>.Offer offer = 2;</code>
   */
  boolean hasOffer();
  /**
   * <code>.Offer offer = 2;</code>
   */
  org.beyene.protocol.tcp.message.Offer getOffer();
  /**
   * <code>.Offer offer = 2;</code>
   */
  org.beyene.protocol.tcp.message.OfferOrBuilder getOfferOrBuilder();

  /**
   * <code>.ForwardOffer forwardOffer = 3;</code>
   */
  boolean hasForwardOffer();
  /**
   * <code>.ForwardOffer forwardOffer = 3;</code>
   */
  org.beyene.protocol.tcp.message.ForwardOffer getForwardOffer();
  /**
   * <code>.ForwardOffer forwardOffer = 3;</code>
   */
  org.beyene.protocol.tcp.message.ForwardOfferOrBuilder getForwardOfferOrBuilder();

  /**
   * <code>.Reservation reservation = 4;</code>
   */
  boolean hasReservation();
  /**
   * <code>.Reservation reservation = 4;</code>
   */
  org.beyene.protocol.tcp.message.Reservation getReservation();
  /**
   * <code>.Reservation reservation = 4;</code>
   */
  org.beyene.protocol.tcp.message.ReservationOrBuilder getReservationOrBuilder();

  /**
   * <code>.ReservationAction reservationAction = 5;</code>
   */
  boolean hasReservationAction();
  /**
   * <code>.ReservationAction reservationAction = 5;</code>
   */
  org.beyene.protocol.tcp.message.ReservationAction getReservationAction();
  /**
   * <code>.ReservationAction reservationAction = 5;</code>
   */
  org.beyene.protocol.tcp.message.ReservationActionOrBuilder getReservationActionOrBuilder();

  /**
   * <code>.ReservationPaymentOption paymentOptions = 6;</code>
   */
  boolean hasPaymentOptions();
  /**
   * <code>.ReservationPaymentOption paymentOptions = 6;</code>
   */
  org.beyene.protocol.tcp.message.ReservationPaymentOption getPaymentOptions();
  /**
   * <code>.ReservationPaymentOption paymentOptions = 6;</code>
   */
  org.beyene.protocol.tcp.message.ReservationPaymentOptionOrBuilder getPaymentOptionsOrBuilder();

  public org.beyene.protocol.tcp.message.Message.MsgCase getMsgCase();
}
