// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dtos.proto

package org.beyene.protocol.tcp.message;

public interface OfferOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Offer)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string source = 1;</code>
   */
  java.lang.String getSource();
  /**
   * <code>string source = 1;</code>
   */
  com.google.protobuf.ByteString
      getSourceBytes();

  /**
   * <code>string id = 2;</code>
   */
  java.lang.String getId();
  /**
   * <code>string id = 2;</code>
   */
  com.google.protobuf.ByteString
      getIdBytes();

  /**
   * <code>double price = 3;</code>
   */
  double getPrice();

  /**
   * <code>double energy = 4;</code>
   */
  double getEnergy();

  /**
   * <code>.google.protobuf.Timestamp date = 5;</code>
   */
  boolean hasDate();
  /**
   * <code>.google.protobuf.Timestamp date = 5;</code>
   */
  com.google.protobuf.Timestamp getDate();
  /**
   * <code>.google.protobuf.Timestamp date = 5;</code>
   */
  com.google.protobuf.TimestampOrBuilder getDateOrBuilder();

  /**
   * <code>int32 window = 6;</code>
   */
  int getWindow();
}
