// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dtos.proto

package org.beyene.protocol.tcp.message;

/**
 * Protobuf type {@code ReservationAction}
 */
public  final class ReservationAction extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:ReservationAction)
    ReservationActionOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ReservationAction.newBuilder() to construct.
  private ReservationAction(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ReservationAction() {
    action_ = 0;
    argument_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private ReservationAction(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            org.beyene.protocol.tcp.message.Reservation.Builder subBuilder = null;
            if (reservation_ != null) {
              subBuilder = reservation_.toBuilder();
            }
            reservation_ = input.readMessage(org.beyene.protocol.tcp.message.Reservation.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(reservation_);
              reservation_ = subBuilder.buildPartial();
            }

            break;
          }
          case 16: {
            int rawValue = input.readEnum();

            action_ = rawValue;
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            argument_ = s;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.beyene.protocol.tcp.message.Dto.internal_static_ReservationAction_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.beyene.protocol.tcp.message.Dto.internal_static_ReservationAction_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.beyene.protocol.tcp.message.ReservationAction.class, org.beyene.protocol.tcp.message.ReservationAction.Builder.class);
  }

  public static final int RESERVATION_FIELD_NUMBER = 1;
  private org.beyene.protocol.tcp.message.Reservation reservation_;
  /**
   * <code>.Reservation reservation = 1;</code>
   */
  public boolean hasReservation() {
    return reservation_ != null;
  }
  /**
   * <code>.Reservation reservation = 1;</code>
   */
  public org.beyene.protocol.tcp.message.Reservation getReservation() {
    return reservation_ == null ? org.beyene.protocol.tcp.message.Reservation.getDefaultInstance() : reservation_;
  }
  /**
   * <code>.Reservation reservation = 1;</code>
   */
  public org.beyene.protocol.tcp.message.ReservationOrBuilder getReservationOrBuilder() {
    return getReservation();
  }

  public static final int ACTION_FIELD_NUMBER = 2;
  private int action_;
  /**
   * <code>.Action action = 2;</code>
   */
  public int getActionValue() {
    return action_;
  }
  /**
   * <code>.Action action = 2;</code>
   */
  public org.beyene.protocol.tcp.message.Action getAction() {
    @SuppressWarnings("deprecation")
    org.beyene.protocol.tcp.message.Action result = org.beyene.protocol.tcp.message.Action.valueOf(action_);
    return result == null ? org.beyene.protocol.tcp.message.Action.UNRECOGNIZED : result;
  }

  public static final int ARGUMENT_FIELD_NUMBER = 3;
  private volatile java.lang.Object argument_;
  /**
   * <code>string argument = 3;</code>
   */
  public java.lang.String getArgument() {
    java.lang.Object ref = argument_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      argument_ = s;
      return s;
    }
  }
  /**
   * <code>string argument = 3;</code>
   */
  public com.google.protobuf.ByteString
      getArgumentBytes() {
    java.lang.Object ref = argument_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      argument_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (reservation_ != null) {
      output.writeMessage(1, getReservation());
    }
    if (action_ != org.beyene.protocol.tcp.message.Action.ACCEPT.getNumber()) {
      output.writeEnum(2, action_);
    }
    if (!getArgumentBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, argument_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (reservation_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getReservation());
    }
    if (action_ != org.beyene.protocol.tcp.message.Action.ACCEPT.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(2, action_);
    }
    if (!getArgumentBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, argument_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.beyene.protocol.tcp.message.ReservationAction)) {
      return super.equals(obj);
    }
    org.beyene.protocol.tcp.message.ReservationAction other = (org.beyene.protocol.tcp.message.ReservationAction) obj;

    if (hasReservation() != other.hasReservation()) return false;
    if (hasReservation()) {
      if (!getReservation()
          .equals(other.getReservation())) return false;
    }
    if (action_ != other.action_) return false;
    if (!getArgument()
        .equals(other.getArgument())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasReservation()) {
      hash = (37 * hash) + RESERVATION_FIELD_NUMBER;
      hash = (53 * hash) + getReservation().hashCode();
    }
    hash = (37 * hash) + ACTION_FIELD_NUMBER;
    hash = (53 * hash) + action_;
    hash = (37 * hash) + ARGUMENT_FIELD_NUMBER;
    hash = (53 * hash) + getArgument().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.beyene.protocol.tcp.message.ReservationAction parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.beyene.protocol.tcp.message.ReservationAction parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.beyene.protocol.tcp.message.ReservationAction parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.beyene.protocol.tcp.message.ReservationAction parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.beyene.protocol.tcp.message.ReservationAction parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.beyene.protocol.tcp.message.ReservationAction parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.beyene.protocol.tcp.message.ReservationAction parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.beyene.protocol.tcp.message.ReservationAction parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.beyene.protocol.tcp.message.ReservationAction parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static org.beyene.protocol.tcp.message.ReservationAction parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.beyene.protocol.tcp.message.ReservationAction parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.beyene.protocol.tcp.message.ReservationAction parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.beyene.protocol.tcp.message.ReservationAction prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code ReservationAction}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:ReservationAction)
      org.beyene.protocol.tcp.message.ReservationActionOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.beyene.protocol.tcp.message.Dto.internal_static_ReservationAction_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.beyene.protocol.tcp.message.Dto.internal_static_ReservationAction_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.beyene.protocol.tcp.message.ReservationAction.class, org.beyene.protocol.tcp.message.ReservationAction.Builder.class);
    }

    // Construct using org.beyene.protocol.tcp.message.ReservationAction.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (reservationBuilder_ == null) {
        reservation_ = null;
      } else {
        reservation_ = null;
        reservationBuilder_ = null;
      }
      action_ = 0;

      argument_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.beyene.protocol.tcp.message.Dto.internal_static_ReservationAction_descriptor;
    }

    @java.lang.Override
    public org.beyene.protocol.tcp.message.ReservationAction getDefaultInstanceForType() {
      return org.beyene.protocol.tcp.message.ReservationAction.getDefaultInstance();
    }

    @java.lang.Override
    public org.beyene.protocol.tcp.message.ReservationAction build() {
      org.beyene.protocol.tcp.message.ReservationAction result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public org.beyene.protocol.tcp.message.ReservationAction buildPartial() {
      org.beyene.protocol.tcp.message.ReservationAction result = new org.beyene.protocol.tcp.message.ReservationAction(this);
      if (reservationBuilder_ == null) {
        result.reservation_ = reservation_;
      } else {
        result.reservation_ = reservationBuilder_.build();
      }
      result.action_ = action_;
      result.argument_ = argument_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.beyene.protocol.tcp.message.ReservationAction) {
        return mergeFrom((org.beyene.protocol.tcp.message.ReservationAction)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.beyene.protocol.tcp.message.ReservationAction other) {
      if (other == org.beyene.protocol.tcp.message.ReservationAction.getDefaultInstance()) return this;
      if (other.hasReservation()) {
        mergeReservation(other.getReservation());
      }
      if (other.action_ != 0) {
        setActionValue(other.getActionValue());
      }
      if (!other.getArgument().isEmpty()) {
        argument_ = other.argument_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      org.beyene.protocol.tcp.message.ReservationAction parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (org.beyene.protocol.tcp.message.ReservationAction) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private org.beyene.protocol.tcp.message.Reservation reservation_;
    private com.google.protobuf.SingleFieldBuilderV3<
        org.beyene.protocol.tcp.message.Reservation, org.beyene.protocol.tcp.message.Reservation.Builder, org.beyene.protocol.tcp.message.ReservationOrBuilder> reservationBuilder_;
    /**
     * <code>.Reservation reservation = 1;</code>
     */
    public boolean hasReservation() {
      return reservationBuilder_ != null || reservation_ != null;
    }
    /**
     * <code>.Reservation reservation = 1;</code>
     */
    public org.beyene.protocol.tcp.message.Reservation getReservation() {
      if (reservationBuilder_ == null) {
        return reservation_ == null ? org.beyene.protocol.tcp.message.Reservation.getDefaultInstance() : reservation_;
      } else {
        return reservationBuilder_.getMessage();
      }
    }
    /**
     * <code>.Reservation reservation = 1;</code>
     */
    public Builder setReservation(org.beyene.protocol.tcp.message.Reservation value) {
      if (reservationBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        reservation_ = value;
        onChanged();
      } else {
        reservationBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.Reservation reservation = 1;</code>
     */
    public Builder setReservation(
        org.beyene.protocol.tcp.message.Reservation.Builder builderForValue) {
      if (reservationBuilder_ == null) {
        reservation_ = builderForValue.build();
        onChanged();
      } else {
        reservationBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.Reservation reservation = 1;</code>
     */
    public Builder mergeReservation(org.beyene.protocol.tcp.message.Reservation value) {
      if (reservationBuilder_ == null) {
        if (reservation_ != null) {
          reservation_ =
            org.beyene.protocol.tcp.message.Reservation.newBuilder(reservation_).mergeFrom(value).buildPartial();
        } else {
          reservation_ = value;
        }
        onChanged();
      } else {
        reservationBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.Reservation reservation = 1;</code>
     */
    public Builder clearReservation() {
      if (reservationBuilder_ == null) {
        reservation_ = null;
        onChanged();
      } else {
        reservation_ = null;
        reservationBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.Reservation reservation = 1;</code>
     */
    public org.beyene.protocol.tcp.message.Reservation.Builder getReservationBuilder() {
      
      onChanged();
      return getReservationFieldBuilder().getBuilder();
    }
    /**
     * <code>.Reservation reservation = 1;</code>
     */
    public org.beyene.protocol.tcp.message.ReservationOrBuilder getReservationOrBuilder() {
      if (reservationBuilder_ != null) {
        return reservationBuilder_.getMessageOrBuilder();
      } else {
        return reservation_ == null ?
            org.beyene.protocol.tcp.message.Reservation.getDefaultInstance() : reservation_;
      }
    }
    /**
     * <code>.Reservation reservation = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        org.beyene.protocol.tcp.message.Reservation, org.beyene.protocol.tcp.message.Reservation.Builder, org.beyene.protocol.tcp.message.ReservationOrBuilder> 
        getReservationFieldBuilder() {
      if (reservationBuilder_ == null) {
        reservationBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            org.beyene.protocol.tcp.message.Reservation, org.beyene.protocol.tcp.message.Reservation.Builder, org.beyene.protocol.tcp.message.ReservationOrBuilder>(
                getReservation(),
                getParentForChildren(),
                isClean());
        reservation_ = null;
      }
      return reservationBuilder_;
    }

    private int action_ = 0;
    /**
     * <code>.Action action = 2;</code>
     */
    public int getActionValue() {
      return action_;
    }
    /**
     * <code>.Action action = 2;</code>
     */
    public Builder setActionValue(int value) {
      action_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>.Action action = 2;</code>
     */
    public org.beyene.protocol.tcp.message.Action getAction() {
      @SuppressWarnings("deprecation")
      org.beyene.protocol.tcp.message.Action result = org.beyene.protocol.tcp.message.Action.valueOf(action_);
      return result == null ? org.beyene.protocol.tcp.message.Action.UNRECOGNIZED : result;
    }
    /**
     * <code>.Action action = 2;</code>
     */
    public Builder setAction(org.beyene.protocol.tcp.message.Action value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      action_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.Action action = 2;</code>
     */
    public Builder clearAction() {
      
      action_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object argument_ = "";
    /**
     * <code>string argument = 3;</code>
     */
    public java.lang.String getArgument() {
      java.lang.Object ref = argument_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        argument_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string argument = 3;</code>
     */
    public com.google.protobuf.ByteString
        getArgumentBytes() {
      java.lang.Object ref = argument_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        argument_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string argument = 3;</code>
     */
    public Builder setArgument(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      argument_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string argument = 3;</code>
     */
    public Builder clearArgument() {
      
      argument_ = getDefaultInstance().getArgument();
      onChanged();
      return this;
    }
    /**
     * <code>string argument = 3;</code>
     */
    public Builder setArgumentBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      argument_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:ReservationAction)
  }

  // @@protoc_insertion_point(class_scope:ReservationAction)
  private static final org.beyene.protocol.tcp.message.ReservationAction DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.beyene.protocol.tcp.message.ReservationAction();
  }

  public static org.beyene.protocol.tcp.message.ReservationAction getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ReservationAction>
      PARSER = new com.google.protobuf.AbstractParser<ReservationAction>() {
    @java.lang.Override
    public ReservationAction parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new ReservationAction(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ReservationAction> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ReservationAction> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public org.beyene.protocol.tcp.message.ReservationAction getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

