// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dtos.proto

package org.beyene.protocol.tcp.message;

public interface ReservationPaymentOptionOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ReservationPaymentOption)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.Reservation reservation = 1;</code>
   */
  boolean hasReservation();
  /**
   * <code>.Reservation reservation = 1;</code>
   */
  org.beyene.protocol.tcp.message.Reservation getReservation();
  /**
   * <code>.Reservation reservation = 1;</code>
   */
  org.beyene.protocol.tcp.message.ReservationOrBuilder getReservationOrBuilder();

  /**
   * <code>repeated string options = 2;</code>
   */
  java.util.List<java.lang.String>
      getOptionsList();
  /**
   * <code>repeated string options = 2;</code>
   */
  int getOptionsCount();
  /**
   * <code>repeated string options = 2;</code>
   */
  java.lang.String getOptions(int index);
  /**
   * <code>repeated string options = 2;</code>
   */
  com.google.protobuf.ByteString
      getOptionsBytes(int index);
}
