// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dtos.proto

package org.beyene.protocol.tcp.message;

public interface ReservationOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Reservation)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string request = 1;</code>
   */
  java.lang.String getRequest();
  /**
   * <code>string request = 1;</code>
   */
  com.google.protobuf.ByteString
      getRequestBytes();

  /**
   * <code>string offer = 2;</code>
   */
  java.lang.String getOffer();
  /**
   * <code>string offer = 2;</code>
   */
  com.google.protobuf.ByteString
      getOfferBytes();
}
