// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dtos.proto

package org.beyene.protocol.tcp.message;

public interface ReservationActionOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ReservationAction)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.Reservation reservation = 1;</code>
   */
  boolean hasReservation();
  /**
   * <code>.Reservation reservation = 1;</code>
   */
  org.beyene.protocol.tcp.message.Reservation getReservation();
  /**
   * <code>.Reservation reservation = 1;</code>
   */
  org.beyene.protocol.tcp.message.ReservationOrBuilder getReservationOrBuilder();

  /**
   * <code>.Action action = 2;</code>
   */
  int getActionValue();
  /**
   * <code>.Action action = 2;</code>
   */
  org.beyene.protocol.tcp.message.Action getAction();

  /**
   * <code>string argument = 3;</code>
   */
  java.lang.String getArgument();
  /**
   * <code>string argument = 3;</code>
   */
  com.google.protobuf.ByteString
      getArgumentBytes();
}
