// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dtos.proto

package org.beyene.protocol.tcp.message;

/**
 * Protobuf type {@code ReservationPaymentOption}
 */
public  final class ReservationPaymentOption extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:ReservationPaymentOption)
    ReservationPaymentOptionOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ReservationPaymentOption.newBuilder() to construct.
  private ReservationPaymentOption(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ReservationPaymentOption() {
    options_ = com.google.protobuf.LazyStringArrayList.EMPTY;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private ReservationPaymentOption(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            org.beyene.protocol.tcp.message.Reservation.Builder subBuilder = null;
            if (reservation_ != null) {
              subBuilder = reservation_.toBuilder();
            }
            reservation_ = input.readMessage(org.beyene.protocol.tcp.message.Reservation.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(reservation_);
              reservation_ = subBuilder.buildPartial();
            }

            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();
            if (!((mutable_bitField0_ & 0x00000002) != 0)) {
              options_ = new com.google.protobuf.LazyStringArrayList();
              mutable_bitField0_ |= 0x00000002;
            }
            options_.add(s);
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000002) != 0)) {
        options_ = options_.getUnmodifiableView();
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.beyene.protocol.tcp.message.Dto.internal_static_ReservationPaymentOption_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.beyene.protocol.tcp.message.Dto.internal_static_ReservationPaymentOption_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.beyene.protocol.tcp.message.ReservationPaymentOption.class, org.beyene.protocol.tcp.message.ReservationPaymentOption.Builder.class);
  }

  private int bitField0_;
  public static final int RESERVATION_FIELD_NUMBER = 1;
  private org.beyene.protocol.tcp.message.Reservation reservation_;
  /**
   * <code>.Reservation reservation = 1;</code>
   */
  public boolean hasReservation() {
    return reservation_ != null;
  }
  /**
   * <code>.Reservation reservation = 1;</code>
   */
  public org.beyene.protocol.tcp.message.Reservation getReservation() {
    return reservation_ == null ? org.beyene.protocol.tcp.message.Reservation.getDefaultInstance() : reservation_;
  }
  /**
   * <code>.Reservation reservation = 1;</code>
   */
  public org.beyene.protocol.tcp.message.ReservationOrBuilder getReservationOrBuilder() {
    return getReservation();
  }

  public static final int OPTIONS_FIELD_NUMBER = 2;
  private com.google.protobuf.LazyStringList options_;
  /**
   * <code>repeated string options = 2;</code>
   */
  public com.google.protobuf.ProtocolStringList
      getOptionsList() {
    return options_;
  }
  /**
   * <code>repeated string options = 2;</code>
   */
  public int getOptionsCount() {
    return options_.size();
  }
  /**
   * <code>repeated string options = 2;</code>
   */
  public java.lang.String getOptions(int index) {
    return options_.get(index);
  }
  /**
   * <code>repeated string options = 2;</code>
   */
  public com.google.protobuf.ByteString
      getOptionsBytes(int index) {
    return options_.getByteString(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (reservation_ != null) {
      output.writeMessage(1, getReservation());
    }
    for (int i = 0; i < options_.size(); i++) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, options_.getRaw(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (reservation_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getReservation());
    }
    {
      int dataSize = 0;
      for (int i = 0; i < options_.size(); i++) {
        dataSize += computeStringSizeNoTag(options_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getOptionsList().size();
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.beyene.protocol.tcp.message.ReservationPaymentOption)) {
      return super.equals(obj);
    }
    org.beyene.protocol.tcp.message.ReservationPaymentOption other = (org.beyene.protocol.tcp.message.ReservationPaymentOption) obj;

    if (hasReservation() != other.hasReservation()) return false;
    if (hasReservation()) {
      if (!getReservation()
          .equals(other.getReservation())) return false;
    }
    if (!getOptionsList()
        .equals(other.getOptionsList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasReservation()) {
      hash = (37 * hash) + RESERVATION_FIELD_NUMBER;
      hash = (53 * hash) + getReservation().hashCode();
    }
    if (getOptionsCount() > 0) {
      hash = (37 * hash) + OPTIONS_FIELD_NUMBER;
      hash = (53 * hash) + getOptionsList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.beyene.protocol.tcp.message.ReservationPaymentOption parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.beyene.protocol.tcp.message.ReservationPaymentOption parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.beyene.protocol.tcp.message.ReservationPaymentOption parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.beyene.protocol.tcp.message.ReservationPaymentOption parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.beyene.protocol.tcp.message.ReservationPaymentOption parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.beyene.protocol.tcp.message.ReservationPaymentOption parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.beyene.protocol.tcp.message.ReservationPaymentOption parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.beyene.protocol.tcp.message.ReservationPaymentOption parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.beyene.protocol.tcp.message.ReservationPaymentOption parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static org.beyene.protocol.tcp.message.ReservationPaymentOption parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.beyene.protocol.tcp.message.ReservationPaymentOption parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.beyene.protocol.tcp.message.ReservationPaymentOption parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.beyene.protocol.tcp.message.ReservationPaymentOption prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code ReservationPaymentOption}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:ReservationPaymentOption)
      org.beyene.protocol.tcp.message.ReservationPaymentOptionOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.beyene.protocol.tcp.message.Dto.internal_static_ReservationPaymentOption_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.beyene.protocol.tcp.message.Dto.internal_static_ReservationPaymentOption_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.beyene.protocol.tcp.message.ReservationPaymentOption.class, org.beyene.protocol.tcp.message.ReservationPaymentOption.Builder.class);
    }

    // Construct using org.beyene.protocol.tcp.message.ReservationPaymentOption.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (reservationBuilder_ == null) {
        reservation_ = null;
      } else {
        reservation_ = null;
        reservationBuilder_ = null;
      }
      options_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000002);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.beyene.protocol.tcp.message.Dto.internal_static_ReservationPaymentOption_descriptor;
    }

    @java.lang.Override
    public org.beyene.protocol.tcp.message.ReservationPaymentOption getDefaultInstanceForType() {
      return org.beyene.protocol.tcp.message.ReservationPaymentOption.getDefaultInstance();
    }

    @java.lang.Override
    public org.beyene.protocol.tcp.message.ReservationPaymentOption build() {
      org.beyene.protocol.tcp.message.ReservationPaymentOption result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public org.beyene.protocol.tcp.message.ReservationPaymentOption buildPartial() {
      org.beyene.protocol.tcp.message.ReservationPaymentOption result = new org.beyene.protocol.tcp.message.ReservationPaymentOption(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (reservationBuilder_ == null) {
        result.reservation_ = reservation_;
      } else {
        result.reservation_ = reservationBuilder_.build();
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        options_ = options_.getUnmodifiableView();
        bitField0_ = (bitField0_ & ~0x00000002);
      }
      result.options_ = options_;
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.beyene.protocol.tcp.message.ReservationPaymentOption) {
        return mergeFrom((org.beyene.protocol.tcp.message.ReservationPaymentOption)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.beyene.protocol.tcp.message.ReservationPaymentOption other) {
      if (other == org.beyene.protocol.tcp.message.ReservationPaymentOption.getDefaultInstance()) return this;
      if (other.hasReservation()) {
        mergeReservation(other.getReservation());
      }
      if (!other.options_.isEmpty()) {
        if (options_.isEmpty()) {
          options_ = other.options_;
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          ensureOptionsIsMutable();
          options_.addAll(other.options_);
        }
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      org.beyene.protocol.tcp.message.ReservationPaymentOption parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (org.beyene.protocol.tcp.message.ReservationPaymentOption) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private org.beyene.protocol.tcp.message.Reservation reservation_;
    private com.google.protobuf.SingleFieldBuilderV3<
        org.beyene.protocol.tcp.message.Reservation, org.beyene.protocol.tcp.message.Reservation.Builder, org.beyene.protocol.tcp.message.ReservationOrBuilder> reservationBuilder_;
    /**
     * <code>.Reservation reservation = 1;</code>
     */
    public boolean hasReservation() {
      return reservationBuilder_ != null || reservation_ != null;
    }
    /**
     * <code>.Reservation reservation = 1;</code>
     */
    public org.beyene.protocol.tcp.message.Reservation getReservation() {
      if (reservationBuilder_ == null) {
        return reservation_ == null ? org.beyene.protocol.tcp.message.Reservation.getDefaultInstance() : reservation_;
      } else {
        return reservationBuilder_.getMessage();
      }
    }
    /**
     * <code>.Reservation reservation = 1;</code>
     */
    public Builder setReservation(org.beyene.protocol.tcp.message.Reservation value) {
      if (reservationBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        reservation_ = value;
        onChanged();
      } else {
        reservationBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.Reservation reservation = 1;</code>
     */
    public Builder setReservation(
        org.beyene.protocol.tcp.message.Reservation.Builder builderForValue) {
      if (reservationBuilder_ == null) {
        reservation_ = builderForValue.build();
        onChanged();
      } else {
        reservationBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.Reservation reservation = 1;</code>
     */
    public Builder mergeReservation(org.beyene.protocol.tcp.message.Reservation value) {
      if (reservationBuilder_ == null) {
        if (reservation_ != null) {
          reservation_ =
            org.beyene.protocol.tcp.message.Reservation.newBuilder(reservation_).mergeFrom(value).buildPartial();
        } else {
          reservation_ = value;
        }
        onChanged();
      } else {
        reservationBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.Reservation reservation = 1;</code>
     */
    public Builder clearReservation() {
      if (reservationBuilder_ == null) {
        reservation_ = null;
        onChanged();
      } else {
        reservation_ = null;
        reservationBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.Reservation reservation = 1;</code>
     */
    public org.beyene.protocol.tcp.message.Reservation.Builder getReservationBuilder() {
      
      onChanged();
      return getReservationFieldBuilder().getBuilder();
    }
    /**
     * <code>.Reservation reservation = 1;</code>
     */
    public org.beyene.protocol.tcp.message.ReservationOrBuilder getReservationOrBuilder() {
      if (reservationBuilder_ != null) {
        return reservationBuilder_.getMessageOrBuilder();
      } else {
        return reservation_ == null ?
            org.beyene.protocol.tcp.message.Reservation.getDefaultInstance() : reservation_;
      }
    }
    /**
     * <code>.Reservation reservation = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        org.beyene.protocol.tcp.message.Reservation, org.beyene.protocol.tcp.message.Reservation.Builder, org.beyene.protocol.tcp.message.ReservationOrBuilder> 
        getReservationFieldBuilder() {
      if (reservationBuilder_ == null) {
        reservationBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            org.beyene.protocol.tcp.message.Reservation, org.beyene.protocol.tcp.message.Reservation.Builder, org.beyene.protocol.tcp.message.ReservationOrBuilder>(
                getReservation(),
                getParentForChildren(),
                isClean());
        reservation_ = null;
      }
      return reservationBuilder_;
    }

    private com.google.protobuf.LazyStringList options_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    private void ensureOptionsIsMutable() {
      if (!((bitField0_ & 0x00000002) != 0)) {
        options_ = new com.google.protobuf.LazyStringArrayList(options_);
        bitField0_ |= 0x00000002;
       }
    }
    /**
     * <code>repeated string options = 2;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getOptionsList() {
      return options_.getUnmodifiableView();
    }
    /**
     * <code>repeated string options = 2;</code>
     */
    public int getOptionsCount() {
      return options_.size();
    }
    /**
     * <code>repeated string options = 2;</code>
     */
    public java.lang.String getOptions(int index) {
      return options_.get(index);
    }
    /**
     * <code>repeated string options = 2;</code>
     */
    public com.google.protobuf.ByteString
        getOptionsBytes(int index) {
      return options_.getByteString(index);
    }
    /**
     * <code>repeated string options = 2;</code>
     */
    public Builder setOptions(
        int index, java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureOptionsIsMutable();
      options_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string options = 2;</code>
     */
    public Builder addOptions(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureOptionsIsMutable();
      options_.add(value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string options = 2;</code>
     */
    public Builder addAllOptions(
        java.lang.Iterable<java.lang.String> values) {
      ensureOptionsIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, options_);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string options = 2;</code>
     */
    public Builder clearOptions() {
      options_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string options = 2;</code>
     */
    public Builder addOptionsBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      ensureOptionsIsMutable();
      options_.add(value);
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:ReservationPaymentOption)
  }

  // @@protoc_insertion_point(class_scope:ReservationPaymentOption)
  private static final org.beyene.protocol.tcp.message.ReservationPaymentOption DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.beyene.protocol.tcp.message.ReservationPaymentOption();
  }

  public static org.beyene.protocol.tcp.message.ReservationPaymentOption getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ReservationPaymentOption>
      PARSER = new com.google.protobuf.AbstractParser<ReservationPaymentOption>() {
    @java.lang.Override
    public ReservationPaymentOption parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new ReservationPaymentOption(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ReservationPaymentOption> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ReservationPaymentOption> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public org.beyene.protocol.tcp.message.ReservationPaymentOption getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

