spring:
  main:
    banner-mode: "OFF"

logging:
  level:
    root: "INFO"
    org.springframework.boot: "INFO"
# config can be omitted due to autodiscover when named logback.xml
# logging/config: "classpath:logback.xml"

# https://www.baeldung.com/spring-boot-context-path
server:
  port: "9000"
